### ISSUE TITLE
How to set the window size of images before loading

### ISSUE THREAD

**Issue by zhuzhiyu6839** [zyramedia/ionic-image-loader#32]
![image](https://cloud.githubusercontent.com/assets/24268503/24505449/807f2f0a-158c-11e7-801c-73181a8eaa64.png)

**Comment by ihadeed** [comment]
You can use CSS to do that.

```css
img-loader {
  display: block;
  min-height: 300px; // set it to the height you think your image would be
}
```
